### ISSUE TITLE
How does one join this temple?

### ISSUE THREAD

**Issue by ferrouswheel** [brson/temple-of-rust#1]
It's unclear how to join this temple in my current environment (OSX 10.9.5, Rust version: 1.2.0), but perhaps that's a feature?

If unintended, a faq might cover it, whether the requirements be sacrificing an ancient but personally loved language, or borrowing ownership of one's mutable soul.

**Comment by brson** [comment]
Nice try @ferrouswheel! It takes more than filing a GitHub issue to uncover the secrets of The Temple of Rust.

**Comment by ferrouswheel** [comment]
Curses - foiled again!

![](http://i.imgur.com/g8bGfCf.gif)
